on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite to the GitHub org
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: vector-ui
          label: invite me to the organisation
          repo-token: ${{ secrets.INVITE_TOKEN }}
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}

      - name: Comment after invite
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.INVITE_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            <b>✅ Invitation sent to join the Vector UI GitHub Organisation. Welcome to the community 🎉</b><br><br>
            Don’t forget to make your org membership public so it shows on your profile. 
            Here’s how 👉 https://github.com/orgs/vector-ui/people<br><br>
            Here's a practice repo: https://github.com/vector-ui/<br>
            Remember — contributing to open source is about collaboration, not just code! 🚀

      - name: Close the issue
        uses: peter-evans/close-issue@v3
        with:
          token: ${{ secrets.INVITE_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          comment: "✅ Issue closed automatically after sending the invite. Welcome aboard!"
